site_name: Paradigm Documentation
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/logo.png
  palette:
    primary: white
repo_url: https://github.com/ParadigmAI/paradigm
repo_name: ParadigmAI/paradigm
