site_name: Paradigm Documentation
repo_name: ParadigmAI/paradigm
repo_url: https://github.com/ParadigmAI/paradigm
theme:
  name: material
  # custom_dir: material/.overrides
  favicon: assets/images/favicon.png
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  palette:
    primary: white
  font:
    text: Roboto
    code: Roboto Mono
extra:
  repo:
    facts:
      - latest
      - stars
      - forks

# Page tree
nav:
  - Home: index.md
  - Installation:
    - Locally: Installation/Locally.md
    - On AWS: Installation/On_AWS.md
  - Tutorials:
    - Basic Pipeline: Tutorials/basic_pipeline.md
  - Support:
    - Reach out: Support/Reach_out.md