site_name: Paradigm Documentation
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  palette:
    primary: white
repo_url: https://github.com/ParadigmAI/paradigm
repo_name: ParadigmAI/paradigm
extra:
  repo:
    facts:
      - latest
      - stars
      - releases
